### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lpil** [alphasights/guides#23]
Hey guys!

I was being nosy, and I found some broken links.

- The link to features (https://github.com/alphasights/guides/blob/master/protocols/features) in the main README.
- The link to heap (https://github.com/alphasights/guides/blob/master/protocols/rails/heapanalytics.com) in the rails README.

Anyway. I like what you've got here. I might have to steal the PR one ;)

All the best,
Louis

**Comment by isab** [comment]
https://github.com/alphasights/guides/pull/24
